---
AWSTemplateFormatVersion: '2010-09-09'
Description: RDS
Parameters:
  DbPassword:
    Type: String
    NoEcho: 'true'
    MinLength: '6'
    MaxLength: '20'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must match pattern [a-zA-Z0-9] and be from 6 to 20 chars in length.
  PublicSubnet1:
    Type: AWS::EC2::Subnet
  PublicSubnet1:
    Type: AWS::EC2::Subnet
  SourceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      SubnetIds:
      - Ref: PublicSubnet1
      - Ref: PublicSubnet2
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Open database for access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        SourceSecurityGroupId:
          Ref: SourceSecurityGroup
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      StorageType: gp2
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: root
      MasterUserPassword:
        Ref: DbPassword
      VPCSecurityGroups:
      - Fn::GetAtt:
        - DBSecurityGroup
        - GroupId
      PubliclyAccessible: 'false'
      DBSubnetGroupName:
        Ref: DBSubnetGroup
Outputs:
  VPC:
    Description: The ID of the VPC created
    Value:
      Ref: VPC
